version: '3'
services:
  postgre:
    container_name: postgre
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-writer}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Abc123567.}
      PGDATA: /data/postgres
    volumes:
      - ${ROOT_DATA_DIR_PATH}/postgres/data:/data/postgres
    ports:
      - "5432:5432"
    restart: ${RESTART_POLICY}

  pgvector:
    container_name: pgvector
    image: ankane/pgvector:v0.4.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-writer}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Abc123567.}
      PGDATA: /data/postgres
    volumes:
      - ${ROOT_DATA_DIR_PATH}/pgvector/data:/data/postgres
    ports:
      - "5433:5432"
    restart: ${RESTART_POLICY}

  magic-assistant:
    container_name: magic-assistant
    image: mojingsmart/magic-assistant:${MAGIC_ASSISTANT_VERSION}
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ../config/magic_assistant.yml:/config/magic_assistant.yml
      - ${LLM_MODEL_PATH}:/opt/magic_assistant/models/public/llm_model
      - ${TEXT_EMBEDDING_MODEL_PATH}:/opt/magic_assistant/models/public/text_embedding_model
    ports:
      - "${MAGIC_ASSISTANT_PORT}:8080"
#    depends_on:
#      - postgre
#      - pgvector
    restart: ${RESTART_POLICY}
