model:
    llm:
      # supported model_types: fake, transformers_llm
        model_type: transformers_llm
        model_path: /opt/magic_assistant/models/mine/mojing-llm-13b

    embedding:
        text:
            model_path: /opt/magic_assistant/models/public/text_embedding_model

web:
    port: 8080

agent:
    max_loop_count: 10
    output_intermediate_steps: True
    user_confirm_and_adjust: False
    memory_size: 3

misc:
    language_code: en

db:
    postgre:
        url: postgresql://writer:Abc123567.@127.0.0.1:5432/mojing

vector:
    type: pgvector
    pgvector:
        url: postgresql://writer:Abc123567.@127.0.0.1:5433/mojing
    milvus:
        host: 127.0.0.1
        port: 19530
oss:
    access_key: minio_writer
    secret_key: minio_writer.098765
    endpoint: 127.0.0.1:9100
    type: minio
