model:
    llm:
      # supported model_types: fake, transform_llm, vicuna
        model_type: vicuna
        model_path: /opt/magic_assistant/models/public/llm_model

    embedding:
        text:
            model_path: /opt/magic_assistant/models/public/text_embedding_model

web:
    port: 8080

agent:
    max_loop_count: 10
    output_intermediate_steps: True
    user_confirm_and_adjust: False
    memory_size: 3

misc:
    language_code: en

db:
    postgre:
        url: postgresql://writer:Abc123567.@192.168.1.7:5432/mojing

vector:
    type: pgvector
    pgvector:
        url: postgresql://writer:Abc123567.@192.168.1.7:5433/mojing
